version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "7001:7001"  # Application port
    restart: always
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379  # Default Redis port

  redis:
    image: redis:alpine
    ports:
      - "7000:6379"  # Exposing Redis port
